- docs/User-Interface-UI/Custom-CSS-Snippets.md
See https://discord.com/channels/559159668438728723/644934273459290145/1048659825627766914
> Added snippet to place performer image in background

- docs/Beginner-Guides/Guide-To-Scraping.md
- Fix alignment so that images are indented the same amount as the text
- Adds spacing between steps so images are closer to the current step than the following step, visually indicating where images "belong"
> Update "Guide to Scraping" Formatting

- in-app-manual/configuration.md
Upcoming feature https://github.com/stashapp/stash/pull/3419
> Simple hardware encoding

- in-app-manual/keyboardshortcuts.md
Mirrored from https://github.com/stashapp/stash/pull/3740
> Filter query

- in-app-manual/keyboardshortcuts.md
From https://github.com/stashapp/stash/pull/3946
> Details page redesign

- add-ons/scripts.md
Added new third party script - StashTagSkins for people who don't want 2500 tags, but want the most popular 200 or so.
> Add StashTagSkins to the Third Party Scripts

- getting-started/installation/freenas-truenas.md
Added some steps to make stash run as a daemon in a background process and not outputting messages to the console. Also configurable config location, a way to config the user/group that stash runs as, and start at boot. Testet on my own system successfully.
> Update freenas-truenas docs with rc.script and more

- user-interface-ui/themes/modern-dark.md
Implement Theme-Fix for latest stash app version.
See [#4238](https://github.com/stashapp/stash/issues/4238) for more infos.
> Fix: Update modern-dark.md

- networking/reverse-proxy.md
> update Caddy v2 reverse proxy

- in-app-manual/scraping/scraperdevelopment.md
From https://github.com/stashapp/stash/pull/4200
> Javascript scraper postprocess

- in-app-manual/plugins.md
From https://github.com/stashapp/stash/pull/4260
> Plugin assets, external scripts and CSP overrides + UI plugin dependencies

- in-app-manual/plugins/uipluginapi.md
From https://github.com/stashapp/stash/pull/4256
> UI Plugin API

- getting-started/installation/macos.md
Update install options to include .app and unified binary.
> Update macOS installation

- in-app-manual/plugins.md
- in-app-manual/scraping.md
From https://github.com/stashapp/stash/pull/4364
> Default package sources

- in-app-manual/tasks/autotagging.md
Port from https://github.com/stashapp/stash/pull/4490
> Add note for auto tag

- home.md
> Update typo in home.md

- add-ons/utilities.md
Just changed the description and added a screenshot.
> Update utilities for Stash_Helper.md

- add-ons/userscripts.md
I've updated my github username, so updating it in the links here.
> update halorrr username

- in-app-manual/configuration.md
Port from https://github.com/stashapp/stash/pull/4566
> Developer option: extra blob paths

- in-app-manual/plugins/uipluginapi.md
Port from https://github.com/stashapp/stash/pull/4546
> Plugin api improvements

- in-app-manual/keyboardshortcuts.md
Port from https://github.com/stashapp/stash/pull/4532
> Scene play and o-counter history view and editing

- in-app-manual/plugins/uipluginapi.md
Port from https://github.com/stashapp/stash/pull/4492
> Implement UI event dispatcher/listener

- in-app-manual/tasks.md
From https://github.com/stashapp/stash/pull/4113
> Add scan option to force gallery zip rescan

- getting-started/installation/synology.md
Updating the installation process on Synology that I wrote a few years ago. 
This improves how it is done based on past years experiences.
> Improved and updated Synology installation

- frequently-asked-questions.md
This is the documentation update for https://github.com/stashapp/stash/pull/4910
> Add example for custom SSL certificate files

- builder/build.ts
AxiosError: Request failed with status code 429
> Try to fix error

- .github/workflows/mkdocs-ci.yml
- builder/plugin.ts
closes #103 
at least not 429, not sure if it's detecting it properly
> [builder] use full github REST api

- builder/repositories/plugins/blackstar3000-stash-plugins.yml
- builder/repositories/plugins/ceequester-CommunityScripts.yml
- builder/repositories/plugins/coderduo-stash-plugins.yml
- builder/repositories/plugins/crudecreations-set-image-pornpics.yml
- builder/repositories/plugins/jsmthy-stash-plugins.yml
- builder/repositories/plugins/sneakyninja256-stash-plugins.yml
- builder/repositories/plugins/withoutpants-stash-plugin-prototypes.yml
> new plugin indicies
